In [3]:
import pandas as pd
import numpy as np

import re      #Text cleaning ke liye use hota hai like numbers, symbols remove karna
import nltk
nltk.download('stopwords')          #Stopwords = common words (like: is, the, and, in)
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ninga\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

### Load Data

In [60]:
import pandas as pd

df = pd.read_csv("spam.csv", encoding="latin-1", sep=None,engine="python")

df = df[['v1', 'v2']]
df.columns = ['label', 'text']

df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [61]:
df.shape

(5572, 2)

In [62]:
df.isnull().sum()

label    0
text     0
dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   5572 non-null   object
 1   text    5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

### Text Preprocessing

In [65]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

## 🔄 Applying Text Cleaning

In [66]:
df['clean_text'] = df['text'].apply(clean_text)

df[['text','clean_text']].head()

,text,clean_text
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,"Nah I don't think he goes to usf, he lives aro...",nah think goes usf lives around though

Common mistake

Not_to_do  =raw text pe TF-IDF lagana
do = clean_text pe lagana

## 🔢 Vectorization

In [67]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['clean_text'])
print(X.shape)

(5572, 7546)

### Label Encoding

In [68]:
y = df['label'].map({'ham': 0, 'spam': 1})

### Train-test split

In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [70]:
print(X_train.shape)
print(X_test.shape)

(4457, 7546)
(1115, 7546)

### Model training and Evaluation

In [76]:
model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion matrix:\n",cm)

Accuracy: 0.9668161434977578
Precision: 1.0
Recall: 0.7533333333333333
F1 Score: 0.8593155893536122

Confusion matrix:
 [[965   0]
 [ 37 113]]


## 🚀 Email Spam Detection System

### 🔹 Key Highlights
- 🧹 Performed text preprocessing (cleaning, stopword removal)
- 🔢 Converted text into numerical features using **TF-IDF Vectorization**
- 🤖 Trained a **Multinomial Naive Bayes** model for classification

### 📊 Results
- 🎯 Achieved ~96% Accuracy
- ✅ High Precision (near perfect spam detection)
- ⚖️ Strong F1-Score indicating balanced performance

### 💡 Summary
This model efficiently classifies messages as **Spam or Not Spam**, demonstrating the effectiveness of NLP techniques in real-world text classification problems.