In [25]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

### Load Data

In [26]:
df = pd.read_csv("house_price_data.csv")

In [27]:
df.head()

,Area_SqFt,BHK,Location,Age_Years,Floor_Level,Furnished_Status,Price_Lakhs
0,NaN,3,Suburban,15.0,19,Fully-Furnished,207.56
1,4007.0,3,Urban,30.0,19,Unfurnished,224.32
2,1360.0,1,Suburban,10.0,4,Fully-Furnished,80.20
3,NaN,5,Suburban,15.0,4,Fully-Furnished,141.73
4,1630.0,1,Urban,7.0,11,Unfurnished,91.15

### Handle Missing Values

In [28]:
df.isnull().sum()

Area_SqFt           15
BHK                  0
Location            36
Age_Years           10
Floor_Level          0
Furnished_Status     0
Price_Lakhs          0
dtype: int64

In [29]:
cat_cols = df.select_dtypes(include='object')
df['Furnished_Status'] = df['Furnished_Status'].astype('category').cat.codes #label Enoding

In [31]:
df['Area_SqFt'] = df['Area_SqFt'].fillna(df['Area_SqFt'].mean())
df['Age_Years'] = df['Age_Years'].fillna(df['Age_Years'].mean())

# feature engineering

In [ ]:
df['Price'] = df['Price_Lakhs'] *1000  # vectorisation

In [38]:
df.drop(['Location'],axis=1,inplace=True)
df.drop(['Price_Lakhs'],axis=1,inplace=True)

### Train-Test split

In [42]:
X = df.drop('Price', axis=1)
y = df['Price']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state=42)

### Model Training

In [43]:
lr = LinearRegression()
lasso = Lasso(alpha=0.1)
ridge = Ridge(alpha=0.1)

In [44]:
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [45]:
lasso.fit(X_train, y_train)
y_pred = lasso.predict(X_test)

In [46]:
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)

### Model Evaluation

In [47]:
models = {
    "Linear": lr,
    "Lasso": lasso,
    "Ridge": ridge
}

import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# training + evaluation
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n{name} Model")
    print("R2 Score:", r2_score(y_test, y_pred))
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

Linear Model
R2 Score: 0.9662690530964518
MAE: 5784.396694223476
RMSE: 10935.744215351995

Lasso Model
R2 Score: 0.9662692300968194
MAE: 5784.3950229565335
RMSE: 10935.71552310551

Ridge Model
R2 Score: 0.9662706381644135
MAE: 5784.3350612589265
RMSE: 10935.487268793633

In [54]:
# Lasso (L1) performs feature selection by removing less important features (coefficients → 0),
# while Ridge (L2) reduces overfitting by shrinking coefficients.
# In this dataset, all models perform similarly, indicating low noise and well-structured features.

In [49]:
df.head()

     Area_SqFt  BHK  Age_Years  Floor_Level  Furnished_Status     Price
0  2544.889362    3       15.0           19                 0  207560.0
1  4007.000000    3       30.0           19                 2  224320.0
2  1360.000000    1       10.0            4                 0   80200.0
3  2544.889362    5       15.0            4                 0  141730.0
4  1630.000000    1        7.0           11                 2   91150.0

### New Prediction

In [53]:
new_house = {
    'Area_SqFt': 1200,
    'BHK': 3,
    'Age_Years': 20.0,
    'Floor_Level': 2,
    'Furnished_Status': 1
}



new_house_df = pd.DataFrame([new_house])

predicted_price = model.predict(new_house_df)

print("Predicted Price:", predicted_price[0])

Predicted Price: 88549.72992255009